stages:
  - build
  - deploy

variables:
  REGISTRY: registry.kpinnovative.co.th/paramee/club-report
  BACKEND_IMAGE: $REGISTRY/backend

build-backend:
  stage: build
  image: docker:24
  tags:
    - runner-develop
  services:
    - docker:24-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA -t $BACKEND_IMAGE:latest .
    - docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $BACKEND_IMAGE:latest
  only:
    - master

deploy-secret:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - runner-develop
  script:
    - kubectl apply -f backend/k8s/secret.yaml
  only:
    - master

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - runner-develop
  script:
    - kubectl apply -f backend/k8s/configmap.yaml
    - kubectl apply -f backend/k8s/backend.yaml
    - kubectl rollout restart deployment/clubreport-backend -n cnpapp
    - kubectl rollout restart deployment/cloudflared -n dev-paramee
  only:
    - master
